(defun normalize-to-origin (obj)
  (let ((min-r (apply #'min (mapcar #'car obj)))
        (min-c (apply #'min (mapcar #'cadr obj))))
    (sort (mapcar (lambda (p) (list (- (car p) min-r) (- (cadr p) min-c))) obj)
          (lambda (a b) (if (= (car a) (car b)) (< (cadr a) (cadr b)) (< (car a) (car b)))))))

(defun rotate-90-cw (obj)
  (let* ((norm (normalize-to-origin obj))
         (rotated (mapcar (lambda (p) (list (cadr p) (- (car p)))) norm)))
    (normalize-to-origin rotated)))

(defun detect-mirror (obj)
  (let* ((norm (normalize-to-origin obj))
         (mirrored (mapcar (lambda (p) (list (car p) (- (cadr p)))) norm)))
    (normalize-to-origin mirrored)))

(defun detect-isomorphism (obj-in obj-out)
  (let ((in (normalize-to-origin obj-in))
        (out (normalize-to-origin obj-out)))
    (or (equal in out)
        (equal (rotate-90-cw in) out)
        (equal (rotate-90-cw (rotate-90-cw in)) out)
        (equal (rotate-90-cw (rotate-90-cw (rotate-90-cw in))) out)
        (let ((m (detect-mirror in)))
          (or (equal m out)
              (equal (rotate-90-cw m) out)
              (equal (rotate-90-cw (rotate-90-cw m)) out)
              (equal (rotate-90-cw (rotate-90-cw (rotate-90-cw m))) out))))))

(defun get-move-vector (pair)
  (let* ((in (getf pair :input)) (out (getf pair :output))
         (min-r-in (apply #'min (mapcar #'car in))) (min-c-in (apply #'min (mapcar #'cadr in)))
         (min-r-out (apply #'min (mapcar #'car out))) (min-c-out (apply #'min (mapcar #'cadr out))))
    (list (- min-r-out min-r-in) (- min-c-out min-c-in))))

(defun get-obj-color (obj grid) (nth (cadar obj) (nth (caar obj) grid)))

(defun explain-transform-with-color (pair grid-in grid-out)
  (let* ((in (getf pair :input)) (out (getf pair :output))
         (c-in (get-obj-color in grid-in)) (c-out (get-obj-color out grid-out))
         (move (get-move-vector pair)) (is-iso (detect-isomorphism in out)))
    (format t "~%ACTION REPORT:~%")
    (format t "- Shape: ~A [Color ~D -> ~D]~%" (if is-iso "MATCH" "MISMATCH") c-in c-out)
    (format t "- Move:  Rows: ~D, Cols: ~D~%" (car move) (cadr move))
    (format t "- Morph: ~A~%" (if (equal (normalize-to-origin in) (normalize-to-origin out)) "NONE" "ROTATED/MIRRORED"))))
